### ISSUE TITLE
Translated into English

### ISSUE THREAD

**Issue by LucioD3v** [LucioMSP/GitHub-101#1]
Hello everyone 👋

We need to create an English translation and make sure it works according to the Spanish content.

Main folder: https://github.com/LucioMSP/GitHub-101

Please compare each file with its original in Spanish and, if necessary, send a PR.

**Comment by iSaulX** [comment]
Hi @LucioMSP i made the PR, i try to keep all of this course, i just changed the video links to make sure the content is according to the translations, just need to merge the pull request.
Please, lmk if i can help you with anything else.

**Comment by LucioD3v** [comment]
Thanks a lot @iSaulX !
